export const ADD_EXPENSE = 'ADD_EXPENSE';
export const FETCH_EXPENSE = 'FETCH_EXPENSE';
export const FETCH_EXPENSES = 'FETCH_EXPENSES';
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';
